const {
  DEV_PORT,
  DEV_DATABASE_URL,
  DEV_REDIS_URL,
  DEV_FRONTEND_URL,
  LUMIID_BASE_URL,
  LUMIID_DEV_SECRET_KEY,
} = process.env;

console.log("Running in development mode");

export default {
  PORT: DEV_PORT,
  DATABASE_URL: DEV_DATABASE_URL,
  REDIS_URL: DEV_REDIS_URL,
  FRONTEND_URL: DEV_FRONTEND_URL,
  LUMIID_BASE_URL: LUMIID_BASE_URL,
  LUMIID_SECRET_KEY: LUMIID_DEV_SECRET_KEY,
};
