const {
  PORT,
  DATABASE_URL,
  REDIS_URL,
  FRONTEND_URL,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
} = process.env;

console.log("Running in production mode");

export default {
  PORT,
  DATABASE_URL,
  REDIS_URL,
  FRONTEND_URL,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
};
